export const images = {
    menuIcon: require('./Menu.png'),
    logoIcon: require('./logo.png'),
    bellIcon: require('./bell.png'),
    cartIcon: require('./cart.png'),
    bannerView: require('./sale.jpeg'),
    searchIcon: require('./search.png'),
    banner: require('./smallbanner.jpg'),
    mobile: require('./realme.jpeg'),
    mobile1: require('./samsung.jpg'),
    laptop: require('./laptop.jpeg'),
    loot: require('./Loot.webp'),
    shop: require('./shop.png'),
    supercoin: require('./coin1.png'),
    home: require('./home.png'),
    credit: require('./coin.png'),
    gamezone: require('./game.png'),
    dry: require('./Dry.jpg'),
    sweets: require('./sweets.jpg'),
    swings: require('./swings.jpeg'),
    coin: require('./supercoin.png'),
    next: require('./next.png'),
    nextblue: require('./nextb.png'),
    doll: require('./doll.jpeg'),
    movie1: require('./movie1.jpg'),
    movie2: require('./movie2.jpg'),
    movie3: require('./movie3.webp'),
    movie4: require('./movie4.jpg'),
    gem: require('./gem.png'),
    dollar: require('./dollar.png'),
    word: require('./word.jpg'),
    saga: require('./saga.jpg'),
    leaugue: require('./leaugue.png'),
    guess: require('./guess.jpg'),
    forestmatch: require('./forestmatch.webp'),
    petgame: require('./petgame.png'),
    candy: require('./candy.png'),
    gameicon: require('./gameicon.png'),
    win: require('./win.jpg')



}